name: Deploy Assets
on:
  push:
    branches: [ main ]
    paths:
      - 'stellanav/**'
      - '*.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package Assets
        run: |
          mkdir public
          
          cd stellanav
          zip -r ../public/assets.zip .
          cd ..
          
          find . -maxdepth 1 -type f \
            ! -name "README.md" \
            ! -name ".gitignore" \
            ! -name "version.txt" \
            ! -path "./.github/*" \
            -exec cp {} public/ \;

          echo "${{ github.sha }}" > public/version.txt
          echo "Stella Ether Asset Server" > public/index.html

      - name: Deploy to GH Pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
